//Kevin Thomas CS1A Chapter 2, P. 109, #2

/**************************************************************
* Sales Prediction
* This program estimates how much money the East Coast division of a company will generate.
*
* Input:
* float variable set to 0.62 which represents the 62% that the division brings in.
* Another integer variable set equal to 4600000 because that will be company revenue for this year.
* Output:
* Print out how much the east coast division will bring in based on this formula:
* Amount generated by East Coast Division = 0.62 * total company revenue.
*
**************************************************************/

#include <iostream>
using namespace std;

int main() {
	//Initialize variable set to 4.6million representing the amount of money the company generated in total.
	int totalRevenue = 4600000;
	//Initialize float variable to 0.62 to represent the 62% that the east division makes.
	float percentage = 0.62;
	//Output the amount of money that the east coast division made.
	cout << totalRevenue * percentage << endl;

	return 0;
}
